# Generated by Django 4.2.1 on 2023-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="User name")),
                ("email", models.EmailField(max_length=254, verbose_name="User email")),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
                ("message", models.TextField(max_length=500, verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "New contact"), ("P", "In process"), ("D", "Processed")],
                        default="N",
                        max_length=1,
                        verbose_name="Contact status",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created time")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated time")),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts", "db_table": "contact"},
        )
    ]
