# Generated by Django 4.2.1 on 2023-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.DeleteModel(name="Comment"),
        migrations.AlterField(model_name="post", name="views", field=models.BigIntegerField(default=0)),
    ]
