# Generated by Django 4.2.1 on 2023-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0003_alter_post_author_alter_post_short_desc")]

    operations = [
        migrations.AddField(model_name="post", name="slug", field=models.SlugField(blank=True, null=True, unique=True))
    ]
